import 'dotenv/config';
import bcrypt from 'bcryptjs';
import { PrismaClient } from '@prisma/client';
const prisma=new PrismaClient();
const people=[['Demo Administrator','admin@safehandover.demo','ADMIN','Operations'],['Maya Nurse','nurse@safehandover.demo','NURSE','Nursing'],['Ari Coordinator','coordinator@safehandover.demo','COORDINATOR','Coordination'],['Sam Surgeon','surgeon@safehandover.demo','SURGEON','Surgery'],['Avery Anaesthesia','anaesthesia@safehandover.demo','ANAESTHESIA','Anaesthesia'],['Read Only Viewer','viewer@safehandover.demo','VIEWER','Evaluation']];
try{
 const users={}; for(const [name,email,role,department] of people)users[role]=await prisma.user.upsert({where:{email},update:{},create:{name,email,role,department,passwordHash:await bcrypt.hash('DemoSafe2026!',10)}});
 await prisma.shift.createMany({data:[{name:'Morning',startTime:'07:00',endTime:'15:00',createdBy:users.ADMIN.id},{name:'Evening',startTime:'15:00',endTime:'23:00',createdBy:users.ADMIN.id},{name:'Night',startTime:'23:00',endTime:'07:00',createdBy:users.ADMIN.id}],skipDuplicates:true});
 if(await prisma.patient.count()===0){const patients=[];for(let i=1;i<=100;i++)patients.push({syntheticPatientId:`SYN-${String(i).padStart(4,'0')}`,displayName:`Synthetic Case ${String(i).padStart(3,'0')}`,procedure:['Planned procedure A','Planned procedure B','Planned procedure C'][i%3],scheduledDate:new Date(Date.now()+((i%14)-2)*86400000),status:'SCHEDULED'});await prisma.patient.createMany({data:patients});
 const allPatients=await prisma.patient.findMany({orderBy:{syntheticPatientId:'asc'}});const owners=[users.NURSE,users.COORDINATOR,users.SURGEON,users.ANAESTHESIA];const statuses=['OPEN','IN_PROGRESS','BLOCKED','RESOLVED','OVERDUE','ESCALATED'];const risks=['LOW','MEDIUM','HIGH','CRITICAL'];const categories=['CONSENT','LAB','ALLERGY','MEDICATION','IMAGING','ANAESTHESIA','DOCUMENTATION','EQUIPMENT'];const hs=[];
 for(let i=0;i<100;i++)hs.push(await prisma.handover.create({data:{patientId:allPatients[i].id,fromShift:['Morning','Evening','Night'][i%3],toShift:['Evening','Night','Morning'][i%3],createdBy:users.NURSE.id,summary:`Synthetic shift handover ${i+1}`,status:i%4===0?'ACKNOWLEDGED':'TRANSFERRED',...(i%4===0?{acknowledgedAt:new Date(),acknowledgedBy:users.COORDINATOR.id}:{})}}));
 for(let i=0;i<160;i++){const patient=allPatients[i%100];const status=statuses[i%6];const deadline=new Date(Date.now()+((i%7)-3)*86400000);const a=await prisma.safetyAction.create({data:{handoverId:hs[i%100].id,patientId:patient.id,title:['Consent verification incomplete','Lab result pending','Confirm allergy record','Equipment readiness check','Anaesthesia review pending'][i%5],description:`Synthetic unresolved-check scenario ${i+1}. Verify and document according to local procedure.`,riskLevel:risks[i%4],category:categories[i%8],status,ownerId:i%11===0?null:owners[i%4].id,deadline:i%13===0?null:deadline,createdBy:users.NURSE.id,...(status==='RESOLVED'?{resolvedAt:new Date(),resolutionNote:'Synthetic scenario marked documented complete.'}:{})}});for(let n=0;n<1+i%2;n++)await prisma.subsequentEvent.create({data:{safetyActionId:a.id,eventType:['OWNER_ACKNOWLEDGED','LAB_RESULT_RECEIVED','SHIFT_CHANGED','STATUS_NOTE'][n%4],description:`Synthetic workflow event ${n+1} for scenario ${i+1}.`,createdBy:owners[(i+n)%4].id,eventTime:new Date(Date.now()-(n*3600000))}});}
 }
 if(await prisma.validationFeedback.count()===0)await prisma.validationFeedback.createMany({data:[
  {role:'Nurse',taskTested:'SIMULATED persona: review unresolved shift transfer',rating:4,comment:'SIMULATED persona response only: named owners help clarify follow-up.',observedIssue:'Dense action lists may need sorting.'},
  {role:'Coordinator',taskTested:'SIMULATED persona: identify overdue action',rating:4,comment:'SIMULATED persona response only: deadline visibility is useful for workflow review.',observedIssue:'Shift filters should be easy to find.'},
  {role:'Surgeon',taskTested:'SIMULATED persona: inspect high-risk open item',rating:3,comment:'SIMULATED persona response only: status and risk are easy to scan.',observedIssue:'Risk entry depends on user judgement.'},
  {role:'Anaesthesia',taskTested:'SIMULATED persona: acknowledge incoming handover',rating:4,comment:'SIMULATED persona response only: acknowledgement adds a receipt record.',observedIssue:'No connection to external schedules.'},
  {role:'Administrator',taskTested:'SIMULATED persona: review audit and metrics',rating:3,comment:'SIMULATED persona response only: audit details support retrospective review.',observedIssue:'Prototype metrics do not generalize.'}
 ]});
 console.log('Seed complete: six demo users, 100 synthetic patients, 100 handovers, 160 synthetic actions, subsequent events, five clearly labeled simulated feedback entries, and reproducible experiment outputs.');
}finally{await prisma.$disconnect();}
