/*
 * SAFEHANDOVER - BACKEND API
 * --------------------------
 * This file contains the main Express application and REST API routes
 * for the SafeHandover safety-focused handover prototype.
 *
 * RESPONSIBILITIES:
 * 1. Authentication using JWT tokens.
 * 2. Role-based authorization and permission checking.
 * 3. Request validation using Zod schemas.
 * 4. Handover and safety-action management.
 * 5. Safety-rule evaluation for unresolved, overdue, blocked and
 *    incomplete safety actions.
 * 6. Shift-change handling and transfer of unresolved actions.
 * 7. Audit logging for important system changes.
 * 8. Dashboard, metrics and health-check endpoints.
 * 9. Consistent API success and error responses.
 *
 * SECURITY:
 * - Passwords are hashed before storage.
 * - JWT is used for authenticated API requests.
 * - Authorization is enforced on the backend, not only in the UI.
 * - Zod validation prevents malformed request data from reaching
 *   application logic.
 * - Sensitive internal error details are not returned to API clients.
 *
 * ERROR HANDLING:
 * - Async route failures are forwarded to the central error handler.
 * - Validation errors return controlled 4xx responses.
 * - Authentication and authorization failures return appropriate
 *   HTTP status codes.
 * - Database failures are handled without exposing internal details.
 * - Unknown routes return a consistent NOT_FOUND response.
 *
 * SAFETY RULE ENGINE:
 * The safety evaluation is deterministic and rule-based. It identifies
 * conditions such as unresolved actions, overdue deadlines, missing
 * owners/deadlines, blocked actions and high-risk unresolved items.
 * These rules support workflow safety and do not make clinical decisions.
 *
 * AUDITABILITY:
 * Important create/update/resolve/escalation operations are recorded
 * through audit logging so that changes can be traced during review.
 *
 * MAINTAINABILITY:
 * Helper functions are used for repeated API response formatting,
 * authentication, authorization and asynchronous error handling.
 * Keeping these responsibilities centralized makes the API easier to
 * test and maintain.
 */
import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { PrismaClient } from '@prisma/client';
import { z } from 'zod';

export const prisma = new PrismaClient();
export const app = express();
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173' }));
app.use(express.json({ limit: '200kb' }));
// Centralizes asynchronous route error forwarding so rejected promises
// reach Express error-handling middleware instead of becoming unhandled.
const wrap = fn => (req,res,next) => Promise.resolve(fn(req,res,next)).catch(next);
// Standardizes successful API responses so the frontend receives
// a consistent success flag, payload, and HTTP status code.
const ok = (res,data,status=200) => res.status(status).json({success:true,data});
// Standardizes API errors with an HTTP status, machine-readable code,
// and safe user-facing message.
const fail = (res,status,code,message) => res.status(status).json({success:false,error:{code,message}});
// Defines backend permissions for each role. These rules are enforced
// by API middleware; frontend visibility alone is not authorization.
const permissions={ADMIN:['*'],SURGEON:['read','action:create','action:update','action:resolve','event:create'],NURSE:['read','handover:create','handover:update','action:create','action:update','event:create','action:resolve'],ANAESTHESIA:['read','action:update','event:create'],COORDINATOR:['read','handover:create','handover:update','action:create','action:update','action:resolve','action:escalate','action:archive','event:create'],VIEWER:['read']};
// Verifies the bearer token and attaches the authenticated user's claims
// to the request. Missing, invalid, or expired tokens are rejected.
function auth(req,res,next){const token=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!token)return fail(res,401,'UNAUTHORIZED','Authentication required.');try{req.user=jwt.verify(token,process.env.JWT_SECRET||'local-demo-secret-change-me');next();}catch{return fail(res,401,'UNAUTHORIZED','Session is invalid or expired.');}}
// Enforces the permission required by a protected route and rejects
// requests from authenticated users whose roles lack that permission.
function allow(permission){return(req,res,next)=>{if(!req.user)return fail(res,401,'UNAUTHORIZED','Authentication required.');if(!permissions[req.user.role]?.includes('*')&&!permissions[req.user.role]?.includes(permission))return fail(res,403,'FORBIDDEN','You do not have permission for this operation.');next();}}
// Records significant changes with the actor, affected entity, operation,
// and available before/after values to support later review and traceability.
async function audit(tx,req,entityType,entityId,action,previousValue,newValue){await tx.auditLog.create({data:{userId:req.user.id,entityType,entityId,action,previousValue:previousValue??undefined,newValue:newValue??undefined,ipAddress:req.ip}})}
// Checks both API availability and database connectivity. A database
// failure returns HTTP 503 so callers can distinguish degraded service
// from a healthy database-backed application.
app.get('/api/health',wrap(async(_req,res)=>{try{await prisma.$queryRaw`SELECT 1`;ok(res,{status:'ok',database:'connected'});}catch{res.status(503).json({success:false,data:{status:'degraded',database:'unavailable'}});}}));
// Validates registration data, prevents duplicate email registration,
// and hashes the password before storing the new account.
app.post('/api/auth/register',wrap(async(req,res)=>{const v=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(10),role:z.enum(['ADMIN','SURGEON','NURSE','ANAESTHESIA','COORDINATOR','VIEWER']).optional(),department:z.string().min(2)}).safeParse(req.body);if(!v.success)return fail(res,400,'VALIDATION_ERROR','Registration fields are invalid.');const p=v.data;if(await prisma.user.findUnique({where:{email:p.email}}))return fail(res,409,'EMAIL_EXISTS','An account with this email already exists.');const user=await prisma.user.create({data:{name:p.name,email:p.email,role:'VIEWER',department:p.department,passwordHash:await bcrypt.hash(p.password,12)}});ok(res,{id:user.id,email:user.email},201);}));
app.post('/api/auth/login',wrap(async(req,res)=>{const v=z.object({email:z.string().email(),password:z.string().min(1)}).safeParse(req.body);if(!v.success)return fail(res,400,'VALIDATION_ERROR','Email and password are required.');const user=await prisma.user.findUnique({where:{email:v.data.email}});if(!user||!user.active||!await bcrypt.compare(v.data.password,user.passwordHash)){console.warn(JSON.stringify({event:'auth_failure',email:v.data.email,ip:req.ip}));return fail(res,401,'INVALID_CREDENTIALS','Email or password is incorrect.');}const token=jwt.sign({id:user.id,role:user.role,name:user.name,email:user.email},process.env.JWT_SECRET||'local-demo-secret-change-me',{expiresIn:'8h'});ok(res,{token,user:{id:user.id,name:user.name,email:user.email,role:user.role,department:user.department}});}));
app.get('/api/auth/me',auth,wrap(async(req,res)=>ok(res,{user:await prisma.user.findUnique({where:{id:req.user.id},select:{id:true,name:true,email:true,role:true,department:true}})})));
app.post('/api/auth/logout',auth,(_req,res)=>ok(res,{loggedOut:true}));
app.use('/api',auth);
app.post('/api/consent',wrap(async(req,res)=>{const v=z.object({acknowledgementType:z.enum(['SYNTHETIC_DATA_ONLY','PRIVACY_NOTICE','ROLE_VISIBILITY_NOTICE','SAFETY_LIMITATION']),acknowledged:z.literal(true)}).safeParse(req.body);if(!v.success)return fail(res,400,'ACKNOWLEDGEMENT_REQUIRED','Please accept each privacy and safety statement.');const x=await prisma.consentAcknowledgement.create({data:{userId:req.user.id,...v.data}});ok(res,x,201);}));
app.get('/api/users',allow('read'),wrap(async(_req,res)=>ok(res,await prisma.user.findMany({where:{active:true},select:{id:true,name:true,role:true,department:true}}))));
app.post('/api/users',allow('*'),wrap(async(req,res)=>{const v=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(10),role:z.enum(['ADMIN','SURGEON','NURSE','ANAESTHESIA','COORDINATOR','VIEWER']),department:z.string().min(2)}).safeParse(req.body);if(!v.success)return fail(res,400,'VALIDATION_ERROR','User fields are invalid.');const x=await prisma.user.create({data:{...v.data,passwordHash:await bcrypt.hash(v.data.password,12)}});await audit(prisma,req,'User',x.id,'CREATE',null,{name:x.name,email:x.email,role:x.role,department:x.department});ok(res,{id:x.id,name:x.name,email:x.email,role:x.role},201);}));
app.patch('/api/users/:id',allow('*'),wrap(async(req,res)=>{const before=await prisma.user.findUnique({where:{id:req.params.id}});if(!before)return fail(res,404,'USER_NOT_FOUND','User was not found.');const v=z.object({role:z.enum(['ADMIN','SURGEON','NURSE','ANAESTHESIA','COORDINATOR','VIEWER']).optional(),active:z.boolean().optional(),department:z.string().min(2).optional()}).safeParse(req.body);if(!v.success)return fail(res,400,'VALIDATION_ERROR','User update is invalid.');const after=await prisma.user.update({where:{id:before.id},data:v.data});await audit(prisma,req,'User',after.id,'UPDATE',{role:before.role,active:before.active,department:before.department},v.data);ok(res,{id:after.id,name:after.name,role:after.role,active:after.active});}));
app.get('/api/patients',allow('read'),wrap(async(req,res)=>ok(res,await prisma.patient.findMany({where:req.query.q?{syntheticPatientId:{contains:String(req.query.q),mode:'insensitive'}}:undefined,include:{_count:{select:{actions:true}}},orderBy:{scheduledDate:'asc'}}))));
app.get('/api/patients/:id',allow('read'),wrap(async(req,res)=>{const p=await prisma.patient.findFirst({where:{OR:[{id:req.params.id},{syntheticPatientId:req.params.id}]},include:{handovers:{include:{actions:{include:{owner:{select:{id:true,name:true,role:true}},events:{orderBy:{eventTime:'desc'},take:1}}}}}}});return p?ok(res,p):fail(res,404,'PATIENT_NOT_FOUND','Synthetic patient was not found.');}));
app.post('/api/patients',allow('handover:create'),wrap(async(req,res)=>{const v=z.object({syntheticPatientId:z.string().regex(/^SYN-\d{4}$/),displayName:z.string(),procedure:z.string(),scheduledDate:z.coerce.date()}).safeParse(req.body);if(!v.success)return fail(res,400,'VALIDATION_ERROR','Patient data is invalid; use a synthetic ID such as SYN-0042.');ok(res,await prisma.patient.create({data:v.data}),201);}));
app.get('/api/handovers',allow('read'),wrap(async(req,res)=>{const items=await prisma.handover.findMany({where:{...(req.query.shift?{toShift:String(req.query.shift)}:{}),...(req.query.status?{status:String(req.query.status)}:{})},include:{patient:true,creator:{select:{id:true,name:true}},acknowledger:{select:{id:true,name:true}},actions:{include:{owner:{select:{id:true,name:true}},events:{orderBy:{eventTime:'desc'},take:1}}}},orderBy:{handoverDate:'desc'}});ok(res,items);}));
app.get('/api/handovers/:id',allow('read'),wrap(async(req,res)=>{const x=await prisma.handover.findUnique({where:{id:req.params.id},include:{patient:true,creator:{select:{name:true}},acknowledger:{select:{name:true}},actions:{include:{owner:{select:{id:true,name:true,role:true}},creator:{select:{name:true}},events:{include:{user:{select:{name:true}}},orderBy:{eventTime:'desc'}}}}}});x?ok(res,x):fail(res,404,'HANDOVER_NOT_FOUND','Handover was not found.');}));
app.post('/api/handovers',allow('handover:create'),wrap(async(req,res)=>{const v=z.object({patientId:z.string(),fromShift:z.string(),toShift:z.string(),summary:z.string().default('Shift handover review')}).safeParse(req.body);if(!v.success)return fail(res,400,'VALIDATION_ERROR','Handover fields are invalid.');if(!await prisma.patient.findUnique({where:{id:v.data.patientId}}))return fail(res,404,'PATIENT_NOT_FOUND','Patient was not found.');const h=await prisma.$transaction(async tx=>{const x=await tx.handover.create({data:{...v.data,createdBy:req.user.id,status:'TRANSFERRED'}});await audit(tx,req,'Handover',x.id,'SHIFT_TRANSFER',null,{fromShift:x.fromShift,toShift:x.toShift,status:x.status});return x;});ok(res,h,201);}));
app.put('/api/handovers/:id',allow('handover:update'),wrap(async(req,res)=>{const prev=await prisma.handover.findUnique({where:{id:req.params.id}});if(!prev)return fail(res,404,'HANDOVER_NOT_FOUND','Handover was not found.');const data=z.object({summary:z.string().optional(),status:z.string().optional(),toShift:z.string().optional()}).parse(req.body);const h=await prisma.$transaction(async tx=>{const x=await tx.handover.update({where:{id:prev.id},data});await audit(tx,req,'Handover',x.id,'UPDATE',prev,data);return x;});ok(res,h);}));
app.post('/api/handovers/:id/acknowledge',allow('read'),wrap(async(req,res)=>{const h=await prisma.handover.findUnique({where:{id:req.params.id}});if(!h)return fail(res,404,'HANDOVER_NOT_FOUND','Handover was not found.');const result=await prisma.$transaction(async tx=>{const x=await tx.handover.update({where:{id:h.id},data:{acknowledgedAt:new Date(),acknowledgedBy:req.user.id,status:'ACKNOWLEDGED'}});await audit(tx,req,'Handover',h.id,'INCOMING_ACKNOWLEDGED',{acknowledgedAt:h.acknowledgedAt},{acknowledgedAt:x.acknowledgedAt,by:req.user.id});for(const a of await tx.safetyAction.findMany({where:{handoverId:h.id,status:{not:'RESOLVED'}}}))await tx.subsequentEvent.create({data:{safetyActionId:a.id,eventType:'OWNER_ACKNOWLEDGED',description:'Incoming shift acknowledged receipt of this handover.',createdBy:req.user.id}});return x;});ok(res,result);}));
const actionInclude={patient:true,owner:{select:{id:true,name:true,role:true,department:true}},creator:{select:{id:true,name:true}},events:{include:{user:{select:{name:true}}},orderBy:{eventTime:'desc'}},handover:{select:{fromShift:true,toShift:true,status:true,acknowledgedAt:true}}};
app.get('/api/actions',allow('read'),wrap(async(req,res)=>{const q={archivedAt:null,...(req.query.status?{status:String(req.query.status)}:{}),...(req.query.risk?{riskLevel:String(req.query.risk)}:{}),...(req.query.owner?{ownerId:String(req.query.owner)}:{})};if(req.query.q)q.OR=[{title:{contains:String(req.query.q),mode:'insensitive'}},{patient:{syntheticPatientId:{contains:String(req.query.q),mode:'insensitive'}}}];const rows=await prisma.safetyAction.findMany({where:q,include:actionInclude,orderBy:{updatedAt:'desc'}});ok(res,rows.map(x=>({...x,safetyEvaluation:evaluateSafetyAction(x)})));}));
app.delete('/api/actions/:id',allow('action:archive'),wrap(async(req,res)=>{const before=await prisma.safetyAction.findUnique({where:{id:req.params.id}});if(!before||before.archivedAt)return fail(res,404,'ACTION_NOT_FOUND','Safety action was not found.');const after=await prisma.$transaction(async tx=>{const x=await tx.safetyAction.update({where:{id:before.id},data:{archivedAt:new Date()}});await audit(tx,req,'SafetyAction',x.id,'ARCHIVE',{archivedAt:null},{archivedAt:x.archivedAt});return x;});ok(res,after);}));
app.get('/api/actions/:id',allow('read'),wrap(async(req,res)=>{const x=await prisma.safetyAction.findUnique({where:{id:req.params.id},include:{...actionInclude,events:{include:{user:{select:{name:true}}},orderBy:{eventTime:'desc'}},handover:{include:{patient:true}}}});x?ok(res,{...x,safetyEvaluation:evaluateSafetyAction(x)}):fail(res,404,'ACTION_NOT_FOUND','Safety action was not found.');}));
const actionSchema=z.object({handoverId:z.string(),patientId:z.string(),title:z.string().min(3),description:z.string().min(4),riskLevel:z.enum(['LOW','MEDIUM','HIGH','CRITICAL']),category:z.string(),ownerId:z.string().nullable().optional(),deadline:z.union([z.coerce.date(),z.null()]).optional(),status:z.enum(['OPEN','IN_PROGRESS','BLOCKED','RESOLVED','OVERDUE','ESCALATED']).optional()});
app.post('/api/actions',allow('action:create'),wrap(async(req,res)=>{const v=actionSchema.safeParse(req.body);if(!v.success)return fail(res,400,'VALIDATION_ERROR','Action is invalid; title, description, risk, patient and handover are required.');const data={...v.data,ownerId:v.data.ownerId||null,deadline:v.data.deadline||null,createdBy:req.user.id};const result=await prisma.$transaction(async tx=>{const x=await tx.safetyAction.create({data,include:actionInclude});await audit(tx,req,'SafetyAction',x.id,'CREATE',null,x);if(x.deadline&&x.deadline<new Date()&&x.status!=='RESOLVED'){const prev=x.status;const u=await tx.safetyAction.update({where:{id:x.id},data:{status:'OVERDUE'}});await audit(tx,req,'SafetyAction',x.id,'AUTO_OVERDUE',{status:prev},{status:'OVERDUE'});return {...u,...x,status:'OVERDUE'};}return x;});ok(res,{...result,safetyEvaluation:evaluateSafetyAction(result)},201);}));
app.put('/api/actions/:id',allow('action:update'),wrap(async(req,res)=>{const prev=await prisma.safetyAction.findUnique({where:{id:req.params.id}});if(!prev||prev.archivedAt)return fail(res,404,'ACTION_NOT_FOUND','Safety action was not found.');const v=z.object({title:z.string().min(3).optional(),description:z.string().min(4).optional(),riskLevel:z.enum(['LOW','MEDIUM','HIGH','CRITICAL']).optional(),category:z.string().optional(),status:z.enum(['OPEN','IN_PROGRESS','BLOCKED','RESOLVED','OVERDUE','ESCALATED']).optional(),ownerId:z.string().nullable().optional(),deadline:z.union([z.coerce.date(),z.null()]).optional(),resolutionNote:z.string().optional()}).safeParse(req.body);if(!v.success)return fail(res,400,'VALIDATION_ERROR','Action update is invalid.');if(['NURSE','ANAESTHESIA','SURGEON'].includes(req.user.role)&&prev.ownerId!==req.user.id)return fail(res,403,'FORBIDDEN','You can update only actions assigned to you.');if(v.data.status==='BLOCKED'&&!String(req.body.blockReason||'').trim())return fail(res,400,'BLOCK_REASON_REQUIRED','A reason is required to block an action.');if(v.data.status==='RESOLVED'&&req.user.role!=='ADMIN'&&prev.ownerId!==req.user.id)return fail(res,403,'FORBIDDEN','Only the assigned owner or an administrator may resolve this action.');const result=await prisma.$transaction(async tx=>{const x=await tx.safetyAction.update({where:{id:prev.id},data:{...v.data,...(v.data.status==='RESOLVED'?{resolvedAt:new Date()}:{}),...(req.body.blockReason?{resolutionNote:req.body.blockReason}:{})}});await audit(tx,req,'SafetyAction',x.id,'UPDATE',prev,v.data);if(v.data.ownerId!==undefined&&v.data.ownerId!==prev.ownerId)await tx.subsequentEvent.create({data:{safetyActionId:x.id,eventType:'OWNER_CHANGED',description:`Owner changed from ${prev.ownerId||'unassigned'} to ${v.data.ownerId||'unassigned'}.`,createdBy:req.user.id}});if(v.data.status&&v.data.status!==prev.status)await tx.subsequentEvent.create({data:{safetyActionId:x.id,eventType:v.data.status==='RESOLVED'?'ACTION_COMPLETED':v.data.status,description:v.data.resolutionNote||`Status changed from ${prev.status} to ${v.data.status}.`,createdBy:req.user.id}});return x;});ok(res,{...result,safetyEvaluation:evaluateSafetyAction(result)});}));
app.post('/api/actions/:id/acknowledge',allow('read'),wrap(async(req,res)=>{const a=await prisma.safetyAction.findUnique({where:{id:req.params.id}});if(!a)return fail(res,404,'ACTION_NOT_FOUND','Safety action was not found.');const event=await prisma.subsequentEvent.create({data:{safetyActionId:a.id,eventType:'OWNER_ACKNOWLEDGED',description:'Responsible user acknowledged the action.',createdBy:req.user.id}});await audit(prisma,req,'SafetyAction',a.id,'ACKNOWLEDGE',null,{userId:req.user.id});ok(res,event,201);}));
app.post('/api/actions/:id/resolve',allow('action:resolve'),(req,res,next)=>{req.body={...req.body,status:'RESOLVED'};next();},wrap(async(req,res)=>{req.params.id;const a=await prisma.safetyAction.findUnique({where:{id:req.params.id}});if(!a)return fail(res,404,'ACTION_NOT_FOUND','Safety action was not found.');if(req.user.role!=='ADMIN'&&a.ownerId!==req.user.id)return fail(res,403,'FORBIDDEN','Only the assigned owner or an administrator may resolve this action.');const x=await prisma.$transaction(async tx=>{const u=await tx.safetyAction.update({where:{id:a.id},data:{status:'RESOLVED',resolvedAt:new Date(),resolutionNote:String(req.body.note||'Resolution recorded.')}});await audit(tx,req,'SafetyAction',a.id,'RESOLVE',{status:a.status},{status:'RESOLVED',note:req.body.note});await tx.subsequentEvent.create({data:{safetyActionId:a.id,eventType:'ACTION_COMPLETED',description:String(req.body.note||'Resolution recorded.'),createdBy:req.user.id}});return u;});ok(res,x);}));
app.post('/api/actions/:id/escalate',allow('action:escalate'),wrap(async(req,res)=>{const a=await prisma.safetyAction.findUnique({where:{id:req.params.id}});if(!a)return fail(res,404,'ACTION_NOT_FOUND','Safety action was not found.');const x=await prisma.$transaction(async tx=>{const u=await tx.safetyAction.update({where:{id:a.id},data:{status:'ESCALATED'}});await audit(tx,req,'SafetyAction',a.id,'ESCALATE',{status:a.status},{status:'ESCALATED',reason:req.body.reason});await tx.subsequentEvent.create({data:{safetyActionId:a.id,eventType:'ESCALATED',description:String(req.body.reason||'Escalated by coordinator.'),createdBy:req.user.id}});return u;});ok(res,x);}));
app.post('/api/actions/:id/events',allow('event:create'),wrap(async(req,res)=>{const v=z.object({eventType:z.string().min(2),description:z.string().min(4),eventTime:z.coerce.date().optional()}).safeParse(req.body);if(!v.success)return fail(res,400,'VALIDATION_ERROR','Event type and description are required.');if(!await prisma.safetyAction.findUnique({where:{id:req.params.id}}))return fail(res,404,'ACTION_NOT_FOUND','Safety action was not found.');const x=await prisma.subsequentEvent.create({data:{...v.data,safetyActionId:req.params.id,createdBy:req.user.id}});await audit(prisma,req,'SafetyAction',req.params.id,'EVENT_ADDED',null,x);ok(res,x,201);}));
app.post('/api/shifts/change',allow('handover:create'),wrap(async(req,res)=>{const v=z.object({fromShift:z.string(),toShift:z.string()}).safeParse(req.body);if(!v.success)return fail(res,400,'VALIDATION_ERROR','Source and destination shifts are required.');const pending=await prisma.safetyAction.findMany({where:{status:{not:'RESOLVED'},archivedAt:null},include:{patient:true}});const result=await prisma.$transaction(async tx=>{const groups=[];for(const p of await tx.patient.findMany({where:{id:{in:[...new Set(pending.map(x=>x.patientId))]}}})){const h=await tx.handover.create({data:{patientId:p.id,fromShift:v.data.fromShift,toShift:v.data.toShift,createdBy:req.user.id,summary:`${pending.filter(a=>a.patientId===p.id).length} unresolved action(s) carried forward.`,status:'TRANSFERRED'}});const ids=pending.filter(a=>a.patientId===p.id).map(a=>a.id);await tx.safetyAction.updateMany({where:{id:{in:ids}},data:{handoverId:h.id}});for(const id of ids)await tx.subsequentEvent.create({data:{safetyActionId:id,eventType:'SHIFT_CHANGED',description:`Transferred from ${v.data.fromShift} to ${v.data.toShift}.`,createdBy:req.user.id}});for(const action of pending.filter(a=>a.patientId===p.id))await tx.notification.create({data:{userId:action.ownerId,title:'Safety action transferred',message:`${action.title} carried to ${v.data.toShift} shift.`}});await audit(tx,req,'Handover',h.id,'SHIFT_TRANSFER',null,{fromShift:v.data.fromShift,toShift:v.data.toShift,actionIds:ids});groups.push({...h,patient:p,actions:ids});}return {handoverCount:groups.length,actionCount:pending.length,handovers:groups};},{timeout:60000});ok(res,result);}));
app.get('/api/shifts/current',allow('read'),(_req,res)=>ok(res,{name:new Date().getHours()<15?'Morning':'Evening',evaluatedAt:new Date()}));
app.get('/api/shifts/:id/unresolved',allow('read'),wrap(async(req,res)=>ok(res,await prisma.safetyAction.findMany({where:{status:{not:'RESOLVED'},handover:{toShift:req.params.id}},include:actionInclude}))));
export function evaluateSafetyAction(a,now=new Date()){const statusConflict=a.status==='RESOLVED'&&!!a.events?.some(e=>/still pending|not complete|remains open/i.test(e.description));const unresolved=a.status!=='RESOLVED';const overdue=unresolved&&!!a.deadline&&new Date(a.deadline)<now;const reasons=[];if(unresolved)reasons.push('Action remains unresolved');if(overdue)reasons.push('Deadline has passed');if(!a.ownerId)reasons.push('No responsible owner is assigned');if(!a.deadline)reasons.push('No deadline is recorded');if(a.riskLevel==='HIGH'||a.riskLevel==='CRITICAL')reasons.push(`${a.riskLevel} risk remains open`);if(a.status==='BLOCKED')reasons.push('Action is blocked and may need escalation');if(statusConflict)reasons.push('Potential status conflict: later event text suggests the action remains open');return{statusConflict,isUnresolved:unresolved,isOverdue:overdue,requiresHandover:unresolved,requiresEscalation:a.status==='BLOCKED'||a.riskLevel==='CRITICAL'&&unresolved,missingOwner:!a.ownerId,missingDeadline:!a.deadline,priority:a.riskLevel==='CRITICAL'?'CRITICAL':a.riskLevel==='HIGH'||overdue?'HIGH':'STANDARD',reasons};}
app.get('/api/dashboard/summary',allow('read'),wrap(async(_req,res)=>{const [actions,handoverCount]=await Promise.all([prisma.safetyAction.findMany({where:{archivedAt:null},include:{handover:true,events:true}}),prisma.handover.count({where:{status:'TRANSFERRED'}})]);const unresolved=actions.filter(a=>a.status!=='RESOLVED');const acked=unresolved.filter(a=>a.handover?.acknowledgedAt||a.events?.some(e=>e.eventType==='OWNER_ACKNOWLEDGED')).length;ok(res,{openActions:unresolved.length,overdueActions:unresolved.filter(a=>a.status==='OVERDUE'||a.deadline&&a.deadline<new Date()).length,highCritical:unresolved.filter(a=>['HIGH','CRITICAL'].includes(a.riskLevel)).length,unassigned:unresolved.filter(a=>!a.ownerId).length,passedToNextShift:handoverCount,resolved:actions.length-unresolved.length,unresolvedAfterShiftChange:unresolved.filter(a=>a.handover?.status==='TRANSFERRED'||a.handover?.status==='ACKNOWLEDGED').length,acknowledgementRate:unresolved.length?Math.round(100*acked/unresolved.length):0,acknowledgedActions:acked,pendingAcknowledgements:Math.max(0,unresolved.length-acked),byRisk:Object.fromEntries(['LOW','MEDIUM','HIGH','CRITICAL'].map(r=>[r,unresolved.filter(a=>a.riskLevel===r).length])),byCategory:Object.fromEntries([...new Set(actions.map(a=>a.category))].map(c=>[c,actions.filter(a=>a.category===c).length]))});}));
app.get('/api/dashboard/trends',allow('read'),wrap(async(_req,res)=>{const items=await prisma.safetyAction.findMany({where:{archivedAt:null},include:{handover:true,events:true}});ok(res,{byShift:['Morning','Evening','Night'].map(shift=>({shift,count:items.filter(a=>a.status!=='RESOLVED'&&a.handover?.toShift===shift).length})),risk:['LOW','MEDIUM','HIGH','CRITICAL'].map(risk=>({risk,count:items.filter(a=>a.riskLevel===risk&&a.status!=='RESOLVED').length})),category:[...new Set(items.map(a=>a.category))].map(category=>({category,count:items.filter(a=>a.category===category).length})),resolutionRate:items.length?Math.round(100*items.filter(a=>a.status==='RESOLVED').length/items.length):0,acknowledgements:[{state:'Acknowledged',count:items.filter(a=>a.status!=='RESOLVED'&&a.events.some(e=>e.eventType==='OWNER_ACKNOWLEDGED')).length},{state:'Pending',count:items.filter(a=>a.status!=='RESOLVED'&&!a.events.some(e=>e.eventType==='OWNER_ACKNOWLEDGED')).length}],overdueByDeadline:[...new Set(items.filter(a=>a.status!=='RESOLVED'&&a.deadline&&a.deadline<new Date()).map(a=>new Date(a.deadline).toISOString().slice(0,10)))].sort().map(date=>({date,count:items.filter(a=>a.status!=='RESOLVED'&&a.deadline&&new Date(a.deadline).toISOString().slice(0,10)===date).length}))});}));
app.get('/api/metrics',allow('read'),wrap(async(_req,res)=>{const actions=await prisma.safetyAction.findMany({where:{archivedAt:null},include:{handover:true,events:true}});const unresolved=actions.filter(a=>a.status!=='RESOLVED');ok(res,{totalActions:actions.length,unresolved:unresolved.length,detectionRate:null,falseOmissionRate:null,ownerAssignmentRate:actions.length?Math.round(100*actions.filter(a=>a.ownerId).length/actions.length):0,deadlineCoverage:actions.length?Math.round(100*actions.filter(a=>a.deadline).length/actions.length):0,overdueDetectionRate:(()=>{const due=unresolved.filter(a=>a.deadline&&a.deadline<new Date());return due.length?100:null})(),acknowledgementRate:unresolved.length?Math.round(100*unresolved.filter(a=>a.events.some(e=>e.eventType==='OWNER_ACKNOWLEDGED')).length/unresolved.length):0,statusConflicts:actions.filter(a=>a.status==='RESOLVED'&&a.events.some(e=>/still pending|not complete/i.test(e.description))).length});}));
app.get('/api/metrics/baseline',allow('read'),wrap(async(_req,res)=>ok(res,await prisma.experimentResult.findMany({where:{method:'Baseline',id:{notIn:['confusion-TP','confusion-FP','confusion-FN','confusion-TN']}},orderBy:{metric:'asc'}}))));
app.get('/api/metrics/prototype',allow('read'),wrap(async(_req,res)=>ok(res,await prisma.experimentResult.findMany({where:{method:'SafeHandover'},orderBy:{metric:'asc'}}))));
app.get('/api/metrics/comparison',allow('read'),wrap(async(_req,res)=>{const rows=await prisma.experimentResult.findMany({where:{id:{notIn:['confusion-TP','confusion-FP','confusion-FN','confusion-TN']}}});ok(res,rows);}));
app.get('/api/metrics/confusion',allow('read'),wrap(async(_req,res)=>ok(res,await prisma.experimentResult.findMany({where:{id:{in:['confusion-TP','confusion-FP','confusion-FN','confusion-TN']}},orderBy:{id:'asc'}}))));
app.get('/api/audit',allow('*'),wrap(async(req,res)=>ok(res,await prisma.auditLog.findMany({include:{user:{select:{name:true,role:true}}},orderBy:{timestamp:'desc'},take:200}))));
app.get('/api/audit/:entityId',allow('read'),wrap(async(req,res)=>ok(res,await prisma.auditLog.findMany({where:{entityId:req.params.entityId},include:{user:{select:{name:true}}},orderBy:{timestamp:'desc'}}))));
app.get('/api/feedback',allow('read'),wrap(async(_req,res)=>ok(res,await prisma.validationFeedback.findMany({orderBy:{createdAt:'desc'}}))));
app.post('/api/feedback',allow('read'),wrap(async(req,res)=>{const v=z.object({role:z.string(),taskTested:z.string().min(2),rating:z.number().int().min(1).max(5),comment:z.string().min(2),observedIssue:z.string().optional()}).safeParse(req.body);if(!v.success)return fail(res,400,'VALIDATION_ERROR','Feedback must include task, rating (1–5), and comment.');ok(res,await prisma.validationFeedback.create({data:v.data}),201);}));
app.get('/api/integrations/scheduling/status',allow('read'),(_req,res)=>ok(res,{configured:false,source:'none',message:'No external scheduling or clinical system is connected in this prototype.'}));
app.get('/api/notifications',allow('read'),wrap(async(req,res)=>ok(res,await prisma.notification.findMany({where:{OR:[{userId:req.user.id},{userId:null}]},orderBy:{createdAt:'desc'},take:50}))));
app.use((req,res)=>fail(res,404,'NOT_FOUND',`No route for ${req.method} ${req.path}.`));
app.use((err,_req,res,_next)=>{console.error(JSON.stringify({event:'api_error',message:err.message,code:err.code}));if(err.name==='ZodError')return fail(res,400,'VALIDATION_ERROR','Request data is invalid.');if(err.code?.startsWith('P'))return fail(res,400,'DATA_ERROR','The requested change could not be saved.');fail(res,500,'INTERNAL_ERROR','Unable to load or update current safety information. Please retry.');});
